### ISSUE TITLE
Node.js style guide: 2 space indentation

### ISSUE THREAD

**Issue by djensen47** [stevewillard/grunt-version-check#2]
It's a bit odd that style guides for JavaScript are usually 4 spaces per indent while Node.js is 2 spaces per indent but that's the way it is.

Just my 2 cents.

**Comment by msimerson** [comment]
I'd suggest either closing this, or adopting two space indention soon. Two spaces seems to be the defacto standard (Google JS Style Guide, Felix's Nodejs Style, JavaScript Standard Style).
