### ISSUE TITLE
Different Exit Code Other Than 0 If Updates Are Present

### ISSUE THREAD

**Issue by kmgilbert100** [stevewillard/grunt-version-check#8]
In the case of running with Jenkins etc.. we should probably add a configurable exit code or just a hard coded exit code so for instance 0 = no updates... 1 = updates... etc

thoughts?

**Comment by stevewillard** [comment]
I kind of like the idea of hard coding a few values based on if things need updates. I'll take a shot at adding it.

**Comment by kmgilbert100** [comment]
Could also always add optional callback functions for what to do if it passes / fails

**Comment by sagiegurari** [comment]
is this being developed? can we have some property to enable grunt to fail if updates are detected?

**Comment by stevewillard** [comment]
Sorry, I don't really have time to add this right now, but I would accept a pull request.

**Comment by sagiegurari** [comment]
I'll try to see if I can do that this week.

**Comment by sagiegurari** [comment]
created PR #12
